

// ServicesListItem Page
export const FETCH_SERVICES = 'FETCH_SERVICES_ADMIN';
export const FETCH_SERVICEBYID = 'FETCH_SERVICEBYID_ADMIN';

//ServiceType
export const SERVICE_HOME = 'SERVICE_HOME'
export const SERVICE_ALBUM = 'ALBUM'
export const SERVICE_WEDDING_DRESS = 'WEDDING_DRESS'
export const SERVICE_WEDDING_VIDEO = 'WEDDING_VIDEO'
// Price 
export const SERVICE_FULL_WEDDING_DAY = 'FULL_WEDDING_DAY'







export const MSG_NO_SELECTED_DELETED = 'Vui lòng chọn mục muốn xóa !'





// Action in page

export const ON_CHANGE_MENU = 'ON_CHANGE_MENU'
export const ON_ADDNEW = 'ON_ADDNEW'
export const ON_EDIT = 'ON_EDIT'
export const ON_VIEW_PRICE = 'ON_VIEW_PRICE'

// Youtube prefix
export const YOUTUBE_PREFIX = 'https://www.youtube.com/watch?v='


// tabCode

// Change to edit tab
export const TAB_HOME = 'SERVICE_HOME'
export const TAB_ALBUM_EDIT = 'ALBUM_EDIT'
export const TAB_WEDDING_DRESS_EDIT = 'WEDDING_DRESS_EDIT'
export const TAB_WEDDING_VIDEO_EDIT = 'WEDDING_VIDEO_EDIT'
export const TAB_FULL_WEDDING_DAY_EDIT = 'FULL_WEDDING_DAY_EDIT'

// Change to add new tab
export const TAB_ALBUM_ADD = 'ALBUM_ADD'
export const TAB_WEDDING_DRESS_ADD = 'WEDDING_DRESS_ADD'
export const TAB_WEDDING_VIDEO_ADD = 'WEDDING_VIDEO_ADD'
export const TAB_FULL_WEDDING_DAY_ADD = 'FULL_WEDDING_DAY_ADD'

//Price list
export const TAB_ALBUM_PRICE = 'ALBUM_PRICE'
export const TAB_WEDDING_VIDEO_PRICE = 'WEDDING_VIDEO_PRICE'
export const TAB_FULL_WEDDING_DAY_PRICE = 'FULL_WEDDING_DAY_PRICE'




export const ALBUM_PRICE = 'ALBUM_PRICE'
export const WEDDING_VIDEO_PRICE = 'WEDDING_VIDEO_PRICE'
export const FULL_WEDDING_DAY_PRICE = 'FULL_WEDDING_DAY_PRICE'

// Tabcode - Edit
export const SERVICE_EDIT_ALBUM = 'ALBUM_EDIT'
export const SERVICE_EDIT_DRESS = 'WEDDING_DRESS_EDIT'
export const WEDDING_VIDEO_EDIT = 'WEDDING_VIDEO_EDIT'
export const PRICE_INCLUSIVE_EDIT = 'PRICE_INCLUSIVE_EDIT'

export const SERVICE_ADDNEW_ALBUM = 'SERVICE_ADDNEW_ALBUM'
export const SERVICE_ADDNEW_DRESS = 'SERVICE_ADDNEW_DRESS'
export const SERVICE_ADDNEW_VIDEO = 'SERVICE_ADDNEW_VIDEO'
export const SERVICE_ADDNEW_PRICELIST = 'SERVICE_ADDNEW_PRICELIST'
export const SERVICE_ADDNEW_PRICE_ALBUM = 'SERVICE_ADDNEW_PRICE_ALBUM'
export const SERVICE_ADDNEW_PRICE_VIDEO = 'SERVICE_ADDNEW_PRICE_VIDEO'
export const SERVICE_ADDNEW_PRICE_INCLUSIVE = 'SERVICE_ADDNEW_PRICE_INCLUSIVE'
export const SERVICE_ADDNEW_OTHERS = 'SERVICE_ADDNEW_OTHERS'


export const SERVICE_EDIT_PRICE_ALBUM = 'WEDDING_DRESS_EDIT'
export const SERVICE_EDIT_PRICE_VIDEO = 'WEDDING_DRESS_EDIT'
export const SERVICE_EDIT_PRICE_INCLUSIVE = 'WEDDING_DRESS_EDIT'
export const SERVICE_EDIT_OTHERS = 'WEDDING_DRESS_EDIT'