spring:
  profiles: dev

  datasource:
    username: thanhtam
    password: zaQ@1234
server:
  port: 8433
  https:
    port: 8433
  http:
    port: 8181

---

spring:
  profiles: prod

  datasource:
    username: root
    password: zaQ@1234
server:
  port: 433
  https:
    port: 433
  http:
    port: 80