spring:
  profiles: dev

  datasource:
    username: thanhtam
    password: zaQ@1234
server:
  port: 8181

---

spring:
  profiles: prod

  datasource:
    username: root
    password: zaQ@1234
server:
  port: 80